-- MySQL Script generated by MySQL Workbench
-- 17 تشرين الثاني, 2016 EET 04:52:30 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema payment_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema payment_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `payment_db` DEFAULT CHARACTER SET utf8 ;
USE `payment_db` ;

-- -----------------------------------------------------
-- Table `payment_db`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_db`.`account` (
  `account_id` MEDIUMTEXT NOT NULL,
  `account_number` MEDIUMTEXT NOT NULL,
  `account_name` VARCHAR(255) NOT NULL COMMENT '		',
  `account_currency` VARCHAR(45) NOT NULL,
  `account_status` INT(11) NOT NULL,
  `customer_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`account_id`, `account_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_db`.`iban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_db`.`iban` (
  `iban_id` MEDIUMTEXT NOT NULL,
  `country_code` VARCHAR(45) NULL,
  `iban_value` VARCHAR(45) NULL,
  PRIMARY KEY (`iban_id`),
  CONSTRAINT `fk_iban_1`
    FOREIGN KEY (`iban_id`)
    REFERENCES `payment_db`.`account` (`account_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_db`.`id_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_db`.`id_table` (
  `table_name` VARCHAR(255) NOT NULL,
  `id` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`table_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_db`.`payment_purpose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_db`.`payment_purpose` (
  `short_code` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`short_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `payment_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_db`.`payment` (
  `order_account_number` MEDIUMTEXT NOT NULL,
  `benficiary_account_iban` MEDIUMTEXT NOT NULL,
  `benficiary_account_name` VARCHAR(255) NOT NULL,
  `payment_amount` DECIMAL NOT NULL,
  `transfer_currency` VARCHAR(45) NOT NULL,
  `payment_date` DATE NOT NULL,
  `payment_purpose` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_account_number`),
  INDEX `fk_payment_1_idx` (`payment_purpose` ASC),
  CONSTRAINT `fk_payment_1`
    FOREIGN KEY (`payment_purpose`)
    REFERENCES `payment_db`.`payment_purpose` (`short_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `payment_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `payment_db`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `payment_db`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `payment_db`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment_db`.`view1`;
USE `payment_db`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
